### ISSUE TITLE
Blocking of versioning queries

### ISSUE THREAD

**Issue by billgeo** [linz/postgresql-tableversion#2]
Small issue, but while the BDE processor query lds.LDS_MaintainSimplifiedLayers(241) is running, any other query that attempts to enable versioning on a table is 'blocked'. 

e.g. SELECT table_version.ver_enable_versioning('admin_bdys','nz_locality');

Presumably some kind of table locking is going on?

**Comment by palmerj** [comment]
Can you confirm this via the pg_stat_activity.waiting view column? If you can also have a look at the pg_locks view to see what relation (you will have to map the oid to pg_class) and what type ("ExclusiveLock" or "RoWExclusiveLock" etc) of locks are active.

**Comment by billgeo** [comment]
Not sure how you wanted to filter the pg_locks view, but here is the output for the relevant PIDs.

Queries were...
select * from pg_stat_activity  order by waiting desc
select * from pg_locks where pid in (3756, 29116) order by pid

[csv.zip](https://github.com/linz/postgresql-tableversion/files/226873/csv.zip)

**Comment by palmerj** [comment]
Can you please decode the "relation" column to the table name within the pg_locks dump? Can do it will a join to the pg_class table.

**Comment by billgeo** [comment]
Here ya go.

[csv_20160421.zip](https://github.com/linz/postgresql-tableversion/files/229244/csv_20160421.zip)

**Comment by palmerj** [comment]
Thanks Bill. Looks like a AccessExclusiveLock is being placed on the table_version.revision table by the ver_enable_versioning function because it needs to drop the admin_bdys_locality_revision table and that table has a foreign key who's parent table is table_version.revision. It seems that dropping foreign keys requires a AccessExclusiveLock on the referenced parent table which was something I was not aware of, but makes sense.

Because the LDS_MaintainSimplifiedLayers function is updating data within other versioned tables that also have foreign keys referencing table_version.revision, the table_version.ver_enable_versioning can't get the AccessExclusiveLock lock it needs.

One option would will be to change the extension to no longer establish foreign keys on the revision table. I actually don't see a big risk in this as there is an expectation that user application code is not altering data in these versioned history tables, only this extension's supporting triggers API functions.

I'll think about this some more.

**Comment by palmerj** [comment]
Confirmed as fixed.
