### ISSUE TITLE
table_version-loader script is present in some postgresql-XX-tableversion packages

### ISSUE THREAD

**Issue by imincik** [linz/postgresql-tableversion#214]
`table_version-loader` script is missing in `postgresql-11-tableversion package`. It is present in all other `postgresql-9.5|9.6|10-tableversion` packages

**Comment by strk** [comment]
The problem is the presence, not the lack, I've updated the title accordingly.
I'm trying to get CI to fail for this reason in #215 and trying to fix it.

The problem is my `debian/control` seems to only be building a _single_ postgresql package:
```
$ grep Package debian/control
Package: tableversion
Package: postgresql-10-tableversion
```

So everything works for me. Have to figure out how to build packages for all versions instead (I do have `postgresql-server-dev-all` package installed but evidently it is not enough)

**Comment by strk** [comment]
Ok the reason why I'm only building 10 is because of `/usr/share/postgresql-common/supported-versions` returning just `10`... Setting `PG_SUPPORTED_VERSIONS="9.6 10"` helps me debug it
