### ISSUE TITLE
Can't upgrade to new packages 

### ISSUE THREAD

**Issue by billgeo** [linz/postgresql-tableversion#348]
Fix contents on packaging that is preventing upgrades to new packages.

**Comment by l0b0** [comment]
In the case of [this specific package](https://packagecloud.io/linz/test/packages/ubuntu/focal/postgresql-10-tableversion_1.10.1-linz~focal_all.deb) the problem is that there's no `/usr/share/postgresql/10/extension/table_version--1.9.0--1.10.0.sql` file. #361 should give some hints as to whether this is still happening.
