### ISSUE TITLE
Provide PostgreSQL-agnostic debian package

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#95]
The `postgresql-<VERSION>-tableversion` package contains both the extension and the loader and the loader template. Instead it would be useful to have a the extension agnostic parts be in a separate package `tableversion` for other packages to rely upon.

**Comment by strk** [comment]
As of current master 28e7107d45e8191b2cfbaecaf0d5ef2cfd9315a5 there's now a separation between the extension scripts install destination and the non-extension script ones. Is this enough to produce 2 different packages ? I guess it could be done by inclusion/exclusion filters in the packaging configuration script ?

**Comment by strk** [comment]
This problem just started striking hard:
https://travis-ci.org/linz/linz-lds-bde-schema/jobs/442591465#L1123

The problem is with installing multiple packages of table_version for multiple PostgreSQL versions.
Doing so errors out at `apt install` time because all the packages contain the _same_ PostgreSQL-agnostic files (the loader and the template)

**Comment by imincik** [comment]
`linz-lds-bde-schema` depends on `tableversion`. Because `linz-lds-bde-schema` is installed before `tableversion` it pics up default (first) possible `tableversion` version defined in `debian/control` which is 9.6. If we are testing with other PG version, it means another `tableversion` is installed and we are hitting problem.

In https://github.com/linz/linz-lds-bde-schema/pull/123 I moved `tableversion` installation before `linz-lds-bde-schema` and fixed one more problem with dependencies in `linz-bde-schema`.

Travis is OK now. But of course, it doesn't solve this task.

**Comment by strk** [comment]
It stroke again: https://travis-ci.com/linz/bde-processor-deployment/jobs/173433208#L6995

**Comment by strk** [comment]
@imincik I noticed we have the `debian/control` file checked in the git repository, but the actual source is `debian/control.in`, do you remember if there was any good reason to also store the generated `control` file ?

**Comment by imincik** [comment]
I is because `control` file is mandatory to for valid Debian package (but I am not sure if removing it will or will not cause any issues to our packaging tooling)
